# Generated by Django 5.2.1 on 2025-05-19 01:01
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('umur', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('prediction_id', models.IntegerField()),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]