# Generated by Django 5.2.1 on 2025-05-19 01:01
from django.db import migrations, models
def delete_accounts_user(apps, schema_editor):
    # Mengambil model dan memastikan tabel `accounts_user` dihapus jika ada
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS accounts_user CASCADE')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(delete_accounts_user, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('umur', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('prediction_id', models.IntegerField()),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]